from __future__ import annotations

import json


def build_card_generation_prompt(topic: str, level: str, search_results: list[dict]) -> str:
    return (
        "You are an English learning agent.\n\n"
        "The user can often understand English, but cannot actively use expressions.\n"
        "Your job: convert searched English references into active transfer cards.\n\n"
        f"Topic: {topic}\n"
        "Source preference: real-world English articles for ordinary educated readers; do not simplify by reading level.\n"
        f"SearchResults(JSON): {json.dumps(search_results, ensure_ascii=False)}\n\n"
        "Rules:\n"
        "- Generate 1 to 10 high-value learning cards based only on the search material.\n"
        "- Each card teaches exactly one Pattern, Grammar, or Chunk.\n"
        "- Each card must use one exact original excerpt copied verbatim from search material.\n"
        "- The excerpt may be one sentence or multiple consecutive sentences, but it must be a continuous exact substring from the article content.\n"
        "- Put that exact excerpt in originalReference. Do not paraphrase, shorten, polish, or invent it.\n"
        "- Extract one reusable target from that exact excerpt.\n"
        "- chinesePrompt must be a natural Chinese translation prompt for that exact excerpt, not a new scenario.\n"
        "- expectedAnswer must exactly equal originalReference because the user is translating the article excerpt back into English.\n"
        "- No filler cards and no duplicate targets within this card set.\n"
        "- Return JSON only.\n"
        "- The top-level object must be exactly: {\"cards\": [...]}.\n"
        "- Every card object must include exactly these keys with these names:\n"
        "  id, type, title, source, originalReference, extractedFromOriginal, target, "
        "  referenceExample, chinesePrompt, expectedAnswer, mustContain.\n"
        "- source must be an object with exactly: title, site, url.\n"
        "- type must be one of: Pattern, Grammar, Chunk.\n"
        "- Do not rename fields. Do not use aliases like referenceSentence, promptChinese, targetExpression, "
        "expectedEnglish, exampleAnswer, sourceTitle, sourceUrl, or sourceSite.\n"
        "Example JSON shape:\n"
        "{\n"
        "  \"cards\": [\n"
        "    {\n"
        "      \"id\": \"card-1\",\n"
        "      \"type\": \"Pattern\",\n"
        "      \"title\": \"Key role pattern\",\n"
        "      \"source\": {\n"
        "        \"title\": \"Example article\",\n"
        "        \"site\": \"Example Site\",\n"
        "        \"url\": \"https://example.com/article\"\n"
        "      },\n"
        "      \"originalReference\": \"Exact excerpt copied verbatim from the article, possibly more than one sentence.\",\n"
        "      \"extractedFromOriginal\": \"plays a key role in\",\n"
        "      \"target\": \"X plays a key role in Y.\",\n"
        "      \"referenceExample\": \"Daily practice plays a key role in improvement.\",\n"
        "      \"chinesePrompt\": \"请把这段中文还原成英文：...\",\n"
        "      \"expectedAnswer\": \"Exact excerpt copied verbatim from the article, same as originalReference.\",\n"
        "      \"mustContain\": \"plays a key role in\"\n"
        "    }\n"
        "  ]\n"
        "}\n"
    )
